# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60c23b0baea17ef2a4c0dbfb7b1153841439906230a8afa02aab957a61c07f768fe1cdca5db6c1163dcbb89e92e117fcf30b17f2f6bcdb818be64aeec0452583

test:
  secret_key_base: e96400918474000c593a9bf121e1a8e0d6186133b81aa7ffec06793699f40bec12612e573e4fc6d704ebe9e3c131db6c7b20bbe44a5902284be3dd7c4035e30b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
